version: '3'

services:
  login_service:
    build:
      context: ./login_service
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@login_db/login_db
      - JWT_SECRET_KEY=supersecretkey
      - SECRET_KEY=mysecretkey
    depends_on:
      - login_db

  notification_service:
    build:
      context: ./notification_service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://user:password@notification_db/notification_db
      - LOGIN_SERVICE_URL=http://login_service:5000/profile
    depends_on:
      - notification_db

  login_db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: login_db
    ports:
      - "5432:5432"

  notification_db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notification_db
    ports:
      - "5433:5432"
